language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
jobs:
  include:
    - stage: test & cover
      node_js: "21"
      script:
        - npm run cover
        - npm run coverage